### ISSUE TITLE
Nonurgent: Why do you use a footer tag?

### ISSUE THREAD

**Issue by MacKenzieRose** [MacKenzieRose/html-writer#1]
In the solutions file, lines 76 and 86, why have the footer tags been included? @thomasjbradley

Cheers!

MacKenzie

**Comment by thomasjbradley** [comment]
Footer is more than just the bottom of a website. It means like extra metadata about a chunk of content. Since we are using an `<article>` we can use the `<footer>` to denote extra information about the article itself, like time, etc.

**Comment by MacKenzieRose** [comment]
Awesome! Thanks 👍
